//public is a keyword to define access level 
// known as access modifier\ there are couple of them we will learn later 
//private (meaning its accessible in same class)
//if you do not use public on variable (or method)
//it is automatically private
//  Class: indicate this is a class
// phone: identifier, the name of the class 
// {any code need to go in here, can not o outside}
// / The moment the class exist it can be a data type
// meaning, you can cretae a variable of that Type
//you can create a new instance (object) of that type and assign the variable
// and much more
public class Phone {
    // a phone has below 
    // attributes or characteristics 
    // Brand, price, memory size
    // Instance variable | field 
    public String brand ; 
    public Decimal price ;
    public Integer memorySize;

}